"""Initial migration.

Revision ID: db691757f7e0
Revises: 
Create Date: 2024-03-21 15:01:03.141687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db691757f7e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
